name: pokemon-api
version: 0.1.0.0
github: 'githubuser/pokemon-api'
license: BSD-3-Clause
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2024 Author name here'

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/pokemon-api#readme>

dependencies:
  - scotty >= 0.12
  - base >= 4.7 && < 5
  - wreq >= 0.5.3.3
  - lens >= 5.1.1
  - lens-aeson >= 1.2.2
  - text >= 1.2.5.0
  - bytestring >= 0.11.3.1
  - aeson
  - http-conduit >= 2.3.0
  - case-insensitive
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  pokemon-api-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pokemon-api

tests:
  pokemon-api-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pokemon-api
